name: kvstore
description: Abstraction layer for common key-value store libraries.
version: 0.0.1
homepage: https://github.com/camrongiuliani/kvstore

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
